#:kivy 2.3.0
#:import dp kivy.metrics.dp


<SpeedDialAction>
    size: self.sd.action_size * self.sd.animation_progress, self.sd.action_size * self.sd.animation_progress
    x: self.sd.main_x + (self.sd.main_size - self.width) / 2
    y:
        self.sd.main_y + (self.sd.main_size - self.height) / 2 \
        + (self.order + 1) * (self.sd.action_size + self.sd.spacing) \
        * (1 if self.sd.stack_direction == "up" else -1) \
        * self.sd.animation_progress
    opacity: self.sd.animation_progress


<SpeedDial>


<ActionsContent@Widget>
    size_hint: None, None
    size: 0, 0


MDScreen:
    md_bg_color: app.theme_cls.surfaceColor

    # Прозрачный SpeedDial
    SpeedDial:
        id: sd
        expanded: True
        root_icon: "plus"
        main_size: dp(64)
        action_size: dp(56)
        spacing: dp(12)
        edge_padding: dp(16)
        anchor_x: "right"
        anchor_y: "center"
        stack_direction: "up"

        actions_content: actions_content

        MDIconButton:
            id: main_btn
            size_hint: None, None
            style: "tonal"
            radius: [self.height / 6, ]
            size: sd.main_size, sd.main_size
            icon: sd.root_icon
            x: sd.main_x
            y: sd.main_y
            on_release: sd.toggle()

        ActionsContent:
            id: actions_content
            # Экшены:
            SpeedDialAction:
                icon: "map-marker-plus"
                sd: sd
                on_release: app.on_add_point()

            SpeedDialAction:
                icon: "download"
                sd: sd
                on_release: app.on_download()

            SpeedDialAction:
                icon: "chart-bar"
                sd: sd
                on_release: app.on_stats()

            SpeedDialAction:
                icon: "pencil"
                sd: sd
                on_release: app.on_edit()
