<BaseAppScreen>
    screen_manager: screen_manager

    ConfiguredScreenManager:
        id: screen_manager
        name: 'base_screen_manager'
        size_hint: 1, 1
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

#    SideMenu:
#        id: side_menu_left
#        size_hint: 0.2, 1
#        pos_hint: {'left': 0, 'y': 0}
#
#    SideMenu:
#        id: side_menu_right
#        size_hint: 0.2, 1
#        pos_hint: {'right': 1, 'y': 0}
