#:kivy 2.3.0
#:import dp kivy.metrics.dp

<Root>:
    ScreenManager:
        MDScreen:
            name: "content"
            md_bg_color: app.theme_cls.backgroundColor

            MDBoxLayout:
                orientation: "horizontal"
                padding: dp(16)
                spacing: dp(16)

                NavigationRail:
                    id: rail
                    type: "selected"
                    panel_widget: nav_drawer

                    NavigationRailMenuButton:

                    NavigationRailButton:
                        icon: "account"

                    NavigationRailItem:
                        icon: "folder-outline"
                        text: "Файлы"

                    NavigationRailItem:
                        icon: "bookmark-outline"
                        text: "Закладки"

                    NavigationRailItem:
                        icon: "library-outline"
                        text: "Библиотека"

                MDScreen:
                    md_bg_color: app.theme_cls.surfaceColor

                    MDLabel:
                        text: "Content area"
                        halign: "center"
                        valign: "center"
                        adaptive_height: True
                        pos_hint: {"center_x": .5, "center_y": .5}

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, dp(16), dp(16), 0)

        MDBoxLayout:
            orientation: "vertical"
            padding: dp(16)
            spacing: dp(12)

            MDLabel:
                text: "Меню"
                adaptive_height: True

            MDNavigationDrawerItem:
                icon: "home"
                text: "Главная"

            MDNavigationDrawerItem:
                icon: "cog"
                text: "Настройки"

            MDNavigationDrawerItem:
                icon: "information"
                text: "О приложении"
