<MKVLabel>
    text_size:
        (self.width if not self.adaptive_width else None) \
        if not self.adaptive_size else None, \
        None
    color: self.alias_color
    disabled_color: self.alias_disabled_color
    font_size: self.alias_font_size
    line_height: self.alias_line_height
    font_name: self.alias_font_name


<MKVIcon>
    font_style: "Icon"
    adaptive_size: True
    text: self.alias_icon_text
    color: self.alias_icon_color
    source: self.alias_icon_source
